### ISSUE TITLE
research and connect with GW's open science program

### ISSUE THREAD

**Issue by david-lippert-gwu** [gwu-libraries/OSPO#15]
Does GW have an open science program and if so, what is the current scope and goals.

There is an opportunity to align a university OSPO with existing interest and activity focused on
open science, particularly given the observation that open source software is a primary research
object or output. Arguably, universities have expended more effort toward articles and data than
software and researchers are more familiar with the ecosystem for articles and data so they
may be more amenable to support for open source software. Typically, the university Provost
charges a group such as a faculty committee or the university libraries to lead their open
science program. When considering how to position an OSPO, it is worthwhile to speak with the
leadership of the open science program (either the Provost, Chair of faculty committee or Dean
of Libraries/University Librarian).

**Comment by david-lippert** [comment]
I have yet to discover an Open Science organization at GW.  I think the OSPO is the defacto leader in this area for GW.

We are an OSF member, though we have minimal researchers using that tool (at least wrt public projects).  I have also made contact with Anthony Artino who is an Open Science advocate (and now an OSPO stakeholder) in the Medical School.

**Comment by david-lippert** [comment]
closing issue
