### ISSUE TITLE
Create OSPO stakeholder group

### ISSUE THREAD

**Issue by labarba** [gwu-libraries/OSPO#21]
Among Q1 milestones is to form and advisory group—we're calling it **OSPO stakeholder group**, to signal that their role is to be heard on their concerns and aspirations, but not in governance.

Possible members:

1. Ryan Watkins, Graduate School of Education
2. John Helveston, Engineering Management and Systems Engineering 

see new page for more information:
https://gwu.box.com/s/uibv0ba0pnnhwg7xoh2y6hqhjwr68q52

**Comment by david-lippert** [comment]
Continuing to grow the OSPO stakeholder group.  We  now have members from 6 out of 14 schools along with staff and students.  I would like to get full representation from all 14 schools as well as additional student membership.
