### ISSUE TITLE
Create OSPO quick guide pamphlet/handout

### ISSUE THREAD

**Issue by david-lippert-gwu** [gwu-libraries/OSPO#37]
Create something similar to the Create digital studio handout or the quick guide for GW faculty

borrow content from web site.

**Comment by david-lippert** [comment]
Must deliver content to Robin before July 19th

**Comment by david-lippert** [comment]
I submitted pamphlet info to Robin before she left on vacation.  She will finalize and submit for printing.  

She used the following box note as her guide.  Everything above the line is meant to be in the pamphlet.
https://gwu.app.box.com/notes/1462689650182

I will close this when we have the printed pamphlets in hand.

**Comment by david-lippert** [comment]
We have 1000 copies of the GW OSPO brochure available outside of Robin's office.  Please grab a handful to hand out to interested parties.  These were printed by LAI and contain workshop content specific for fall 2024.  New brochures will be printed for the spring, so hand these out freely.
