### ISSUE TITLE
Add form to gather input about GW OSS community

### ISSUE THREAD

**Issue by david-lippert-gwu** [gwu-libraries/OSPO#38]
Create a form and add to the GW OSPO website to capture information about students, faculty, and staff and their OSS projects/repos to help us identify and network with the GW OSS community.

Rather than tracking down people via github, etc. this is an opt-in method.

**Comment by david-lippert** [comment]
Created a new project registry.  Still need to complete the registration workflow so that the OSPO will be notified of new submissions, validate and tidy them up, and then make them available to be displayed on the website.
https://ospo.gwu.edu/project-registry

**Comment by david-lippert** [comment]
Still working on the project registration workflow.  The developers rejected our proposal and our request is likely delayed until after GW cuts over to version 10 of drupal this summer.  In the meantime, we have implemented a manual process that I will publish this week and close this ticket when it goes live.

**Comment by david-lippert** [comment]
The manual process is fine for now.  I'm closing the ticket and we can open a new ticket if we decide to fix this workflow in the future.
