### ISSUE TITLE
Bring gw-ospo GitHub org under gwuniversity "Enterprise" org

### ISSUE THREAD

**Issue by labarba** [gwu-libraries/OSPO#40]
To get the enterprise features, the org must be part of the parent GW org

**Comment by david-lippert** [comment]
This [gw-ospo](https://github.com/gw-ospo) is already a part of the GWU github enterprise.  



![Image](https://github.com/gwu-libraries/OSPO/assets/8987916/cc79444d-aff2-46fd-a8f9-cdb523416131)
