### ISSUE TITLE
Add Mike to: Box, Slack, anything else

### ISSUE THREAD

**Issue by labarba** [gwu-libraries/OSPO#41]

**Comment by s2t2** [comment]
Slack: check
Libraries Profile: check
OSPO Drupal: todo (https://ospo.drupal.gwu.edu/)
OSPO Drupal Profile: todo
OSPO Email Delegation: todo

**Comment by david-lippert** [comment]
added Mike and Lorena as drupal ospo website owners.  Added Mike to the ospo@gwu.edu email

**Comment by david-lippert** [comment]
I think Michael has access to most everything, so I'm closing this ticket.
