### ISSUE TITLE
URSSI Workshop Planning & Support

### ISSUE THREAD

**Issue by david-lippert** [gwu-libraries/OSPO#46]
plan & organize catering, aide coordination, event signage, badging, scheduling, feedback, any logistics, etc.?

**Comment by david-lippert** [comment]
@labarba what is our budget & expectation for catering for this event?  What are the other hosting obligations?

**Comment by labarba** [comment]
I emailed Kyle, Cc you, to get some more parameters for our planning.

**Comment by david-lippert** [comment]
Check out Tonic for upstairs group dinner
Circa will let us reserve outside patio
Pete's for catered coffee & tea

**Comment by david-lippert** [comment]
opened up applications for additional local attendees.  4-5 strong candidates have already applied.

Still need to work through catering and other logistics

**Comment by david-lippert** [comment]
Coordinated with badge office about getting temp badges.  Need to follow up with GW IT to get see about getting temp GW emails which is required for the badges.

**Comment by david-lippert** [comment]
Actions this week

- Contacted Catherine from GW IT who is looking into the badging matter.  Her phone is 571-553-0345
- Manny Teitelbaum reached out to participate.  I recommend he be another aide.  Need to confirm with Kyle
- One student is missing the first day.  Worked a plan with Kyle to allow them to study on their own to try and catch up.
- 5-6 local people have applied for additional local spots.  I gave them a deadline of May 10th.  Not sure how many spaces exactly are available.  Would love help selecting the candidates.

**Comment by david-lippert** [comment]
get quote for tonic room.  40 people.  or Dukes grocery.

**Comment by david-lippert** [comment]
- sent notifications for 4 late local attendees
- sent waiting list emails to other candidates
- attempting to reserve tonic room for June 25th at 6pm (Kyle will need to confirm and pay)
- working with GW IT to get temporary badges for non-local participants
   - Here is ticket ID Your GW Support Ticket Has Been Created: REQ000000566205 (WO0000000210946)
   - Here is spreadsheet with attendees names and emails [URSSI-non-local-participants-June2024.xlsx](https://github.com/user-attachments/files/15540002/URSSI-non-local-participants-June2024.xlsx)

Todo
- Order lunch catering
- Coffee?
