### ISSUE TITLE
Define Project Registry eligibility

### ISSUE THREAD

**Issue by labarba** [gwu-libraries/OSPO#54]
The [Project Registry page](https://ospo.gwu.edu/project-registry) simply says: 

> The Project Registry tracks open source projects at GW
>
> Students, faculty, and staff are encouraged to register publicly available projects to help us recognize and strengthen our GW open source community.

It should have some language about **eligibility** of projects to be listed.

First we need to define clearly those eligibility conditions. At minimum, a project needs to have a public license. Additionally, we might explain that projects should align with the Open Source Definition.

**Comment by labarba** [comment]
**Open Source Definition**: https://opensource.org/osd

**Notes**:

- The license must allow modifications and derived works…
- The license must not discriminate against any person or group of persons…
- The license must not restrict anyone from making use of the program in a specific field of endeavor…
- No provision of the license may be predicated on any individual technology or style of interface…

What about works that are _not software_? The freedoms stipulated above should still be granted. Item 2 of the OSD, however, cannot be applied in that case: "The program must include source code, and must allow distribution in source code…"
We fall back to the **Open Definition**: https://opendefinition.org/od/2.1/en/
One concern is the following requirement: _"the individual elements of the work can be easily accessed and modified."_
In particular, certain multi-media content types do not allow easy modifications and derived works, e.g., videos. Text-based content on PDF format is also difficult to modify to produce derived works, although it is generally possible to export the PDF to an editable format (Word, Google docs). The better scenario is that the content has a _source_ that is also open, e.g., LaTeX or Markdown files.

**Comment by labarba** [comment]
June 19, 2024, email to Alexa:

> We are still defining the strict contours of scope for the Project Registry, and have a range of views within the team. I am of the opinion that the registry should include projects that align with the [Open Source Definition](https://opensource.org/osd), which is of course focused on software. If we embrace a broader scope as OSPO beyond software, in particular welcoming open educational resources, then those projects should align with the [Open Definition](https://opendefinition.org/od/2.1/en/), which applies to other forms of content.
> 
> Your film course materials are licensed under CC-BY-NC, which is an accepted license in the OER world, and satisfies most of the conditions of the Open Definition—except non-discrimination (“The license must not discriminate against any person or group.”) You can read about why a non-commercial rider is problematic in this section of our licensing tutorial 
> https://gw-ospo.github.io/oss-licensing/license_your_own_work.html#what-about-a-non-commercial-cc-license
> 
> In rigor your OER project would not qualify under a strict alignment with open source freedoms, but here is where we remain uncertain within the team, as David holds the view that we should be as inclusive as possible. Given this, and that we still feature just a few projects, your film course remains listed. But in the future we may revisit. In general, regarding multi-media content for educational purposes, my sense is that the Library should have a different place to feature those projects. Currently, it appears that the Library does not have a home for showcasing OER produced at GW. Perhaps we can work with them on that in the future.

**Comment by david-lippert** [comment]
Other OSPOs project registry links

- Georgia Tech
   - https://github.com/gt-ospo/oss-project-explorer
   - https://gt-ospo.github.io/oss-project-explorer/
- JHU
   - https://ospo.library.jhu.edu/open-source-project-catalog/
- Stanford
   - https://opensource.stanford.edu/projects-registry

**Comment by david-lippert** [comment]
Created new [Project Submission Requirements](https://ospo.gwu.edu/project-submission-requirements) page.

Closing this ticket.
