### ISSUE TITLE
[web] Turn pull-down content sections in "Resources" to sub-pages

### ISSUE THREAD

**Issue by labarba** [gwu-libraries/OSPO#56]

**Comment by labarba** [comment]
I would like to expand content under the sections of ["Resources"](https://ospo.gwu.edu/resources):

1. GW tools & infrastructure enabling open source
2. Open Education Resources (OER)
3. Open Access Resources
4. Best Practice Guides & Metrics
5. Funding Opportunities

They should be separated into sub-pages first. "Funding Opportunities" (add "for open source") should be ordered second, above OER and OA. 

BTW, need to use consisted title vs. sentence capitalization.

**Comment by david-lippert** [comment]
I made the small changes you suggested.  I do not understand what you mean by sub-pages, so I'd like clarification.

**Comment by david-lippert** [comment]
I converted each resource that was previously an accordian, into a button that links to a subpage.  Olivia fixed the breadcrumb issue on the Student Awards page.  I'm still not certain if Olivia fixed the logo.  Please let me know if it is still a problem, but I will close this ticket and we can open up a new ticket if there are more issues to be resolved.
